# Makefile.config
# Project: tombseller
# Main settings for makefiles.
# Authors: M. Antonelli, S. Pagan Griso
# Description: Main settings. Add new subdirectories here!
# Special Notes:

#Installation directory
INSTALLDIR=/working/tombseller

#Here go all the directories containing code. Put the main one at the end!
#CODESECTIONS = iomanager datamanager objects main
CODESECTIONS = iomanager datamanager main

#All sections, including special data-content ones, etc.. that is everything needs a Makefile.
SECTIONS = $(CODESECTIONS)

#Include directories
INCLUDEPATH   = -I$(INSTALLDIR)/iomanager -I$(INSTALLDIR)/datamanager -I$(INSTALLDIR)/objects -I$(INSTALLDIR)/main
#Lib directories
LDLIBPATH     = -L$(INSTALLDIR)/iomanager -L$(INSTALLDIR)/datamanager -L$(INSTALLDIR)/objects -L$(INSTALLDIR)/main

#General settings
MAKE 	  = gmake
CXX       = g++
LD        = g++
RM        = /bin/rm
AR	  = ar
ARFLAGS	  = $(nullstring)
#General C++ compiler flags
CXXFLAGS  = -g -Wall -I. $(INCLUDEPATH)
#General Linker flags
LDFLAGS   = -static $(LDLIBPATH)
#General libraries (including -l and -L flags)
LIBS = $(nullstring)

#Rules
.cc.o:
	${CXX} ${CXXFLAGS} -c $< -o $@
